### ISSUE TITLE
Negative numbers in a gaussian fit produce NaN result

### ISSUE THREAD

**Issue by mherrerarendon** [mshrtsr/fitting-rs#22]
The following code results in NaN. 

```rust
let (mu, _, _) = fitting::gaussian::fit(vec![1., 2., 3.].into(), vec![-1., 1., -1.].into())?;
assert_eq!(mu, f64::NAN);
```

If negative numbers are not supported by the Guos algorithm, this function could return Err instead of NaN

**Comment by mherrerarendon** [comment]
Using [try_reduce](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.try_reduce) on this [line](https://docs.rs/fitting/0.3.0/src/fitting/gaussian.rs.html#116) could be a good way to check without adding too much overhead of checking the input separately, except `try_reduce` is nightly...

Could look something like this
```rust
let sum_y_pow2: f64 = y_vals
    .into_iter()
    .try_reduce(|accum, elem| {
        if elem.is_sign_positive() {
            Some(accum + elem.powi(2))
        } else {
            None
        }
    })
    .ok_or(anyhow::anyhow!("No sum"))?
    .ok_or(anyhow::anyhow!("No sum"))?;
```

**Comment by mshrtsr** [comment]
@mherrerarendon 
Thank you for reporting, and sorry it took so long to reply.
I will fix this issue at https://github.com/mshrtsr/fitting-rs/pull/52

**Comment by mherrerarendon** [comment]
Awesome, thank you!
