### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by phil-opp** [mshrtsr/fitting-rs#6]
Hi, I've tried the gaussian fit implementation in this library but its results appear to be incorrect. My test data was the following:

```rust
let x_vec = (0..21).map(f64::from).collect();
let y_vec = vec![
    446.0, 495.0, 549.0, 615.0, 694.0, 1087.0, 16012.0, 16476.0, 4815.0, 1318.0,
    777.0, 722.0, 714.0, 693.0, 681.0, 681.0, 668.0, 643.0, 606.0, 560.0, 512.0
].into();
```

The `fitting-rs` crate returns the following gaussian fitting result for these test values: `[4.6326517102201885, 4.438748232053279, 16683.674991852855]`. 

Below is a plot of these values in comparison with a Python reference implementation:

![image](https://user-images.githubusercontent.com/1131315/94588520-487ca900-0284-11eb-9a4e-c6d85bf22b4d.png)

The blue curve is the test data, the green curve is the result from the `fitting-rs` crate, and the red curve is the result when using `scipy.optimize.curve_fit` in Python (see [this stackoverflow answer](https://stackoverflow.com/a/11507723/866447)). The values calculated from scipy are:

```
Fitted mean =  6.57653369889164
Fitted standard deviation =  0.7894414326527827
Fitted a =  19830.56343766285
```

**Comment by mshrtsr** [comment]
@phil-opp 
Thank you for reporting, and sorry it took so long to reply. 

## Summary

The fitting-rs return low accurate answer for long tail gaussian distribution (GF).
This is not a bug of the program but a known characteristic of the algorithm we use.
We have some workaround to bypass it.

## Reproduction

We could reproduce the situation with your test data.

The fitted curve from `fitting-rs (Guo's)` is significantly away from the test data.

![output](https://user-images.githubusercontent.com/33759872/209906253-c0715ab3-f150-4440-921d-30f03293b747.png)


Results from `scripy.optimize.curve_fit`:

```
Fitted mean =  6.576534508488
Fitted standard deviation =  0.789437712434
Fitted a =  19830.612248005185
```

Results from `fitting-rs (Guo's)`:

```
Fitted mean =  4.632651710220127
Fitted standard deviation =  4.438748232053301
Fitted a =  16683.674991852913
```

## Cause: Guo's algorithm deteriorates for a long-tail GF

`fitting-rs::Gaussian::fit` implements Guo's algorithm.

Guo's algorithm is a gaussian fitting algorithm.  
It tries to find the "true" solution with a non-interactive procedure.

cf. [I. Al-Nahhal, O. A. Dobre, E. Basar, C. Moloney and S. Ikki, "A Fast, Accurate, and Separable Method for Fitting a Gaussian Function [Tips & Tricks]," in IEEE Signal Processing Magazine, vol. 36, no. 6, pp. 157-163, Nov. 2019, doi: 10.1109/MSP.2019.2927685.](https://arxiv.org/pdf/1907.07241.pdf)

(`scripy.optimize.curve_fit` finds an approximate solution with the interactive procedure)

According to the above paper, Guo's algorithm has low accuracy for long-tailed distribution.

## Workaround 1: Slice the tail of the test data

If possible, filtering the tail of test data is the easiest way to get the correct answer.


### Results for short-tailed distribution (3 <= x < 11)

With the filtered part of your test data, we could get the same answer from `scripy.optimize.curve_fit` and `fitting-rs`.

![output-1](https://user-images.githubusercontent.com/33759872/209906838-7a742ff9-9fdf-4ff1-9d50-611154b177a2.png)


Results from `scripy.optimize.curve_fit`:

```
Fitted mean =  6.5765356297
Fitted standard deviation =  0.7894371274
Fitted a =  19830.6196954575
```

Results from `fitting-rs (guo's)`:

```
Fitted mean =  6.482831955106326
Fitted standard deviation =  1.0970420200930318
Fitted a =  17738.39595086066
```

## Workaround 2: Iterate Guo's algorithm

The paper above introduces Guo's algorithm with an iterative procedure, which can increase accuracy for long-tailed distribution.

However, the iterative procedure wasn't efficient for your test data.

### Results with Guo's algorithm with an iterative procedure

number of iterations: 100, 10000

![output-2](https://user-images.githubusercontent.com/33759872/209907849-62d24293-6804-488e-86cf-543d3556b042.png)

Results from `scripy.optimize.curve_fit`:

```
Fitted mean =  6.5765345085
Fitted standard deviation =  0.7894377124
Fitted a =  19830.6122480052
```

Results from `fitting-rs (Guo's)`:

```
Fitted mean =  4.632651710220127
Fitted standard deviation =  4.438748232053301
Fitted a =  16683.674991852913
```

Results from `fitting-rs (Guo's, 100 iterations)`:

```
Fitted mean =  4.6326517102201255
Fitted standard deviation =  4.438748232053626
Fitted a =  16683.674991851403
```

Results from `fitting-rs (Guo's, 10,000 iterations)`:

```
Fitted mean =  4.632651710239668
Fitted standard deviation =  4.438748232047389
Fitted a =  16683.674991781016
```

## Workaround 3: Increase the test data

Generally, the accuracy of the fitting algorithm depends on the amount of test data.

### Results for twice the amount of test data

I used the following test data.

```
test data [   42.0413475332    35.0511734593    17.6614331529    92.6444691075
    27.3999311322    17.6379426741    10.5240362907    43.6023713359
   140.1208316353   670.3596698681  2751.466525975   7833.5681090576
 15193.0737583056 19750.6761857466 17188.2978760121 10042.1807383399
  3908.1955062337  1052.7075702915   193.2331586335    31.3824502956
     8.0492949709    42.775489106     12.23048649      49.8044860964
    19.5313773617    29.9427301152    93.7976460651    23.2826229006
     2.6687303488    41.7511065593    38.0251558866    28.9320419412
     0.8048973518    32.298697015     51.1036760765    25.3402900068
    53.8432425685    51.5671032454    23.6348079253    14.8978990368
    13.4135381931    15.0061579874]
```

![output-4](https://user-images.githubusercontent.com/33759872/209908200-f74612ce-2f44-4624-a429-bb1a4be915f2.png)

Results from `scripy.optimize.curve_fit`:

```
Fitted mean =  6.5767972014
Fitted standard deviation =  0.7912082315
Fitted a =  19830.977268077
```

Results from `fitting-rs (Guo's)`:

```
Fitted mean =  6.602663706648259
Fitted standard deviation =  1.0946277757552922
Fitted a =  17617.453559076108
```

## Ex: Results with noisy but short-tailed data

Despite high noise data, both Guo's and scipy got similar results.

```
test data [ 2  6  4  8 12 17 11 23 21 17 14 18  7 14  8  4  4  8  1  1]
```

![output-5](https://user-images.githubusercontent.com/33759872/209908358-52f334fb-4867-45a2-bab4-6e75266d4d88.png)

Results from `scripy.optimize.curve_fit`:

```
Fitted mean =  8.2766977925
Fitted standard deviation =  4.3718506747
Fitted a =  18.6236249382
```

Results from `fitting-rs (Guo's)`:

```
Fitted mean =  8.540997995662911
Fitted standard deviation =  4.93702931652066
Fitted a =  19.396958411813046
```

**Comment by phil-opp** [comment]
Thanks a lot for the detailed explanation and the possible workarounds! Maybe it makes sense to add a caveat about the low accuracy for long-tailed distributions to the docs?

**Comment by mshrtsr** [comment]
@phil-opp 
I added a limitations note on https://github.com/mshrtsr/fitting-rs/pull/53. Thank you!

**Comment by phil-opp** [comment]
Perfect, thanks!
